config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  resources :caves
  root 'caves#index'
  get 'detect', :controller => :caves, :action => :detect
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cafe.rb
class Cafe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/caves_controller.rb
class CavesController < ApplicationController
  before_action :set_cafe, only: [:show, :edit, :update, :destroy]

  # GET /caves
  # GET /caves.json
  def index
    @caves = Cafe.all
  end

  # GET /caves/1
  # GET /caves/1.json
  def show
  end

  # GET /caves/new
  def new
    @cafe = Cafe.new
  end

  # GET /caves/1/edit
  def edit
  end

  # POST /caves
  # POST /caves.json
  def create
    @cafe = Cafe.new(cafe_params)

    respond_to do |format|
      if @cafe.save
        format.html { redirect_to @cafe, notice: 'Cafe was successfully created.' }
        format.json { render :show, status: :created, location: @cafe }
      else
        format.html { render :new }
        format.json { render json: @cafe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /caves/1
  # PATCH/PUT /caves/1.json
  def update
    respond_to do |format|
      if @cafe.update(cafe_params)
        format.html { redirect_to @cafe, notice: 'Cafe was successfully updated.' }
        format.json { render :show, status: :ok, location: @cafe }
      else
        format.html { render :edit }
        format.json { render json: @cafe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caves/1
  # DELETE /caves/1.json
  def destroy
    @cafe.destroy
    respond_to do |format|
      format.html { redirect_to caves_url, notice: 'Cafe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def detect
    longtitude = 35.6445617
    latitude = 139.66970979999996
    @cafe = Cafe.where(longtitude: longtitude, latitude: latitude)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cafe
      @cafe = Cafe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cafe_params
      params.require(:cafe).permit(:category, :name, :longtitude, :latitude)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caves_helper.rb
module CavesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/caves/_form.html.erb
<%= form_with(model: cafe, local: true) do |form| %>
  <% if cafe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cafe.errors.count, "error") %> prohibited this cafe from being saved:</h2>

      <ul>
      <% cafe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, id: :cafe_category %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :cafe_name %>
  </div>

  <div class="field">
    <%= form.label :longtitude %>
    <%= form.text_field :longtitude, id: :cafe_longtitude %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :cafe_latitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/caves/edit.html.erb
<h1>Editing Cafe</h1>

<%= render 'form', cafe: @cafe %>

<%= link_to 'Show', @cafe %> |
<%= link_to 'Back', caves_path %>

app/views/caves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Caves</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Name</th>
      <th>Longtitude</th>
      <th>Latitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @caves.each do |cafe| %>
      <tr>
        <td><%= cafe.category %></td>
        <td><%= cafe.name %></td>
        <td><%= cafe.longtitude %></td>
        <td><%= cafe.latitude %></td>
        <td><%= link_to 'Show', cafe %></td>
        <td><%= link_to 'Edit', edit_cafe_path(cafe) %></td>
        <td><%= link_to 'Destroy', cafe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cafe', new_cafe_path %>

app/views/caves/new.html.erb
<h1>New Cafe</h1>

<%= render 'form', cafe: @cafe %>

<%= link_to 'Back', caves_path %>

app/views/caves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @cafe.category %>
</p>

<p>
  <strong>Name:</strong>
  <%= @cafe.name %>
</p>

<p>
  <strong>Longtitude:</strong>
  <%= @cafe.longtitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @cafe.latitude %>
</p>

<%= link_to 'Edit', edit_cafe_path(@cafe) %> |
<%= link_to 'Back', caves_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Decafe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "decafe") %>
<h1>Sample App</h1>
<p>
  This is the home page for the
  <a href="http://railstutorial.jp/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "decafe") %>
<h1>Sample App</h1>
<p>
  This is the home page for the
  <a href="http://railstutorial.jp/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "decafe") %>
<h1>Sample App</h1>
<p>
  This is the home page for the
  <a href="http://railstutorial.jp/">Ruby on Rails Tutorial</a>
  sample application.
</p>